name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'samples/tutorial/**'

jobs:
  build:
    name: Android CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest --no-daemon --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Archive APKs
        uses: actions/upload-artifact@v3
        with:
          name: Release-APK
          path: app/build/outputs/apk/release/app-release.apk
          
      - name: Archive Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
